nome = input('Qual é o seu nome?')
print('É um grande prazer ter conheçer', nome,'.')
idade = input('Quantos anos você tem? ')
dia = input('Qual dia você nasceu? ')
mes = input('Qual mês você nasceu? ')
ano = input('Qual ano você nasceu? ')
print('Você nasceu no dia',dia,'do mês de',mes,'do ano de',ano,'e possui',idade,'anos de idade.')
print('Estou certo',nome,'?')
